

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAILED = "PRODUCT_DETAILS_FAILED";

export const PRODUCTS_DETAILS_REQUEST = "PRODUCTS_DETAILS_REQUEST";
export const PRODUCTS_DETAILS_SUCCESS = "PRODUCTS_DETAILS_SUCCESS";
export const PRODUCTS_DETAILS_FAILED = "PRODUCTS_DETAILS_FAILED";

export const PRODUCT_CREATE_OR_UPDATE_REQUEST = "PRODUCT_CREATE_OR_UPDATE_REQUEST";
export const PRODUCT_CREATE_OR_UPDATE_SUCCESS = "PRODUCT_CREATE_OR_UPDATE_SUCCESS";
export const PRODUCT_CREATE_OR_UPDATE_FAILED = "PRODUCT_CREATE_OR_UPDATE_FAILED";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILED = "PRODUCT_DELETE_FAILED";

export const CLEAR_SUCCESS = "CLEAR_SUCCESS";
export const CLEAR_ERROR = "CLEAR_ERROR";

